# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: erpc/sentence.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("erpc/sentence.proto", :syntax => :proto3) do
    add_message "erpc.Sentence" do
      optional :no, :int64, 1
      optional :score, :int64, 2
    end
    add_message "erpc.Sentences" do
      repeated :sentences, :message, 1, "erpc.Sentence"
    end
    add_message "erpc.User" do
      optional :id, :int64, 1
    end
  end
end

module Erpc
  Sentence = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("erpc.Sentence").msgclass
  Sentences = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("erpc.Sentences").msgclass
  User = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("erpc.User").msgclass
end
